name: deeppbs-linux-official
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=12.1
  - pip
  - pip:
      - torch_geometric
      - biopython==1.83
      - logomaker
      - matplotlib==3.5.2
      - networkx
      - pandas==1.4.4
      - pdb2pqr
      - scipy==1.14.1
      - seaborn==0.13.2
      - freesasa==2.2.1
